/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        degreename: {
            type: 'string',
            required: true
        },
        institutionname: {
            type: 'string',
            required: true
        },
        awardingbody: {
            type: 'string',
            required: true
        },
        passingyear: {
            type: 'integer',
            required: true
        },
        result: {
            type: 'string',
            required: true
        },
        academichistoryid: {
            type: 'integer',
            required: false
        },
        personid: {
            type: 'integer',
            required: true
        }
    }
};