/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        date: {
            type: 'date',
            required: true
        },
        invoiceno: {
            type: 'string',
            required: true
        },
        amount: {
            type: "float",
            required: true
        },
        billid: {
            type: 'integer',
            required: false
        },
        customerorderid: {
            type: 'integer',
            required: false
        }
    }
};