/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        addressline1: {
            type: 'string',
            required: true
        },
        addressline2: {
            type: 'string',
            required: true
        },
        city: {
            type: 'string',
            required: true
        },
        country: {
            type: 'string',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        postcode: {
            type: 'string',
            required: true
        },
        contactno: {
            type: 'string',
            required: true
        },
        billingaddressid: {
            type: 'integer',
            required: false
        },
        customerorderid: {
            type: 'integer',
            required: false
        }
    }
};