/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        categoryname: {
            type: 'string',
            required: true
        },
        description: {
            type: 'string',
            required: true
        },
        level: {
            type: 'integer',
            required: true
        },
        hassubcategory: {
            type: 'boolean',
            required: true
        },
        categoryid: {
            type: 'integer',
            required: false
        }
    }
};