/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        categorytype: {
            type: 'string',
            required: true
        },
        accountname: {
            type: 'string',
            required: true
        },
        desription: {
            type: 'string',
            required: true
        },
        undercategory: {
            type: 'string',
            required: true
        },
        naturetype: {
            type: 'string',
            required: true
        },
        chartofaccountid: {
            type: 'integer',
            required: false
        }
    }
};