/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        accountname: {
            type: 'string',
            required: true
        },
        accountno: {
            type: 'string',
            required: true
        },
        joiningdate: {
            type: 'date',
            required: true
        },
        active: {
            type: 'boolean',
            required: true
        },
        suspended: {
            type: 'boolean',
            required: true
        },
        accountcreditlimit: {
            type: "float",
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        clientaccountid: {
            type: 'integer',
            required: false
        },
        clientid: {
            type: 'integer',
            required: true
        },
        organizationid: {
            type: 'integer',
            required: true
        }
    }
};