/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        iteminfo: {
            type: 'string',
            required: true
        },
        quantity: {
            type: "float",
            required: true
        },
        itemprice: {
            type: "float",
            required: true
        },
        contractdetailsid: {
            type: 'integer',
            required: false
        },
        salescontractid: {
            type: 'integer',
            required: true
        }
    }
};