/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        discount: {
            type: "float",
            required: true
        },
        orderdate: {
            type: 'datetime',
            required: true
        },
        receivedate: {
            type: 'datetime',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        ordertotal: {
            type: "float",
            required: true
        },
        customerorderid: {
            type: 'integer',
            required: false
        },
        clientaccountid: {
            type: 'integer',
            required: true
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};