/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        contactno: {
            type: 'string',
            required: true
        },
        departmentname: {
            type: 'string',
            required: true
        },
        location: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        branchid: {
            type: 'integer',
            required: false
        },
        departmentid: {
            type: 'integer',
            required: false
        },
        organizationid: {
            type: 'integer',
            required: false
        },
        createdat: {
            required: true
        },
        updatedat: {
            required: true
        }
    }
};