/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        paymentmadeby: {
            type: 'string',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        disbusrmentpaymentid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        },
        payrollid: {
            type: 'integer',
            required: false
        }
    }
};