/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        joningdate: {
            type: 'date',
            required: true
        },
        leavingdate: {
            type: 'date',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        employeeid: {
            type: 'integer',
            required: false
        },
        warehouseid: {
            type: 'integer',
            required: true
        },
        departmentid: {
            type: 'integer',
            required: true
        },
        branchid: {
            type: 'integer',
            required: true
        },
        factoryid: {
            type: 'integer',
            required: true
        },
        organizationid: {
            type: 'integer',
            required: true
        }
    }
};