/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        designation: {
            type: 'string',
            required: true
        },
        organizationname: {
            type: 'string',
            required: true
        },
        address: {
            type: 'string',
            required: true
        },
        joiningdate: {
            type: 'date',
            required: true
        },
        leavingdate: {
            type: 'date',
            required: true
        },
        employmenthistoryid: {
            type: 'integer',
            required: false
        },
        personid: {
            type: 'integer',
            required: true
        }
    }
};