/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        address: {
            type: 'string',
            required: true
        },
        factoryname: {
            type: 'string',
            required: true
        },
        contactno: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        factoryid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        },
        warehouseid: {
            type: 'integer',
            required: true
        },
        organizationid: {
            type: 'integer',
            required: false
        },
        createdat: {
            required: true
        },
        updatedat: {
            required: true
        }
    }
};