/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        nationality: {
            type: 'string',
            required: true
        },
        passportno: {
            type: 'string',
            required: true
        },
        foreignvehicleid: {
            type: 'integer',
            required: false
        },
        foreignshipmentid: {
            type: 'integer',
            required: true
        }
    }
};