/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        increaseamount: {
            type: "float",
            required: true
        },
        insereseddate: {
            type: 'date',
            required: true
        },
        incrementid: {
            type: 'integer',
            required: false
        },
        monthlyid: {
            type: 'integer',
            required: true
        }
    }
};