/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        shipmentid: {
            type: 'integer',
            required: true
        },
        vehicleid: {
            type: 'integer',
            required: true
        }
    }
};