/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        amount: {
            type: "float",
            required: true
        },
        debitcredit: {
            type: 'string',
            required: true
        },
        invoiceno: {
            type: 'string',
            required: true
        },
        journalid: {
            type: 'integer',
            required: false
        },
        chartofaccountid: {
            type: 'integer',
            required: false
        },
        subsidiaryaccountid: {
            type: 'integer',
            required: true
        },
        transactionid: {
            type: 'integer',
            required: false
        },
        particulars: {
            type: 'string',
            required: true
        }
    }
};