/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        leavedate: {
            type: 'date',
            required: true
        },
        leavefrom: {
            type: 'date',
            required: true
        },
        leaveto: {
            type: 'date',
            required: true
        },
        leavetype: {
            type: 'string',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        totaldays: {
            type: 'integer',
            required: true
        },
        leaveid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};