/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        date: {
            type: 'date',
            required: true
        },
        hscode: {
            type: 'string',
            required: true
        },
        ircercno: {
            type: 'string',
            required: true
        },
        lcafno: {
            type: 'string',
            required: true
        },
        lcafdate: {
            type: 'date',
            required: true
        },
        lcdate: {
            type: 'date',
            required: true
        },
        lcno: {
            type: 'string',
            required: true
        },
        nameofcarrier: {
            type: 'string',
            required: true
        },
        nationality: {
            type: 'string',
            required: true
        },
        placeofloading: {
            type: 'string',
            required: true
        },
        placeofunloading: {
            type: 'string',
            required: true
        },
        vatregistrationno: {
            type: 'string',
            required: true
        },
        currency: {
            type: 'string',
            required: true
        },
        insurancecovernoteno: {
            type: 'string',
            required: true
        },
        recevingbank: {
            type: 'string',
            required: true
        },
        lettercreditid: {
            type: 'integer',
            required: false
        },
        insuranceid: {
            type: 'integer',
            required: true
        },
        subsidiaryaccountid: {
            type: 'integer',
            required: true
        }
    }
};