/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        loanamount: {
            type: "float",
            required: true
        },
        loandate: {
            type: 'date',
            required: true
        },
        payingdate: {
            type: 'date',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        loanid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};