/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        discount: {
            type: "float",
            required: true
        },
        quantity: {
            type: 'integer',
            required: true
        },
        unitprice: {
            type: "float",
            required: true
        },
        total: {
            type: "float",
            required: true
        },
        orderdetailsid: {
            type: 'integer',
            required: false
        },
        customerorderid: {
            type: 'integer',
            required: false
        },
        itemid: {
            type: 'integer',
            required: false
        }
    }
};