/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        organizationname: {
            type: 'string',
            required: true
        },
        address: {
            type: 'string',
            required: true
        },
        city: {
            type: 'string',
            required: true
        },
        contactno: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        logo: {
            type: 'string',
            required: true
        },
        organizationid: {
            type: 'integer',
            required: false
        },
        country: {
            type: 'string',
            required: true
        },
        createdat: {
            required: true
        },
        updatedat: {
            required: true
        }
    }
};