/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        overtimedate: {
            type: 'date',
            required: true
        },
        fromtime: {
            type: 'datetime',
            required: true
        },
        totalhour: {
            type: "float",
            required: true
        },
        totime: {
            type: 'datetime',
            required: true
        },
        overtimeid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};