/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        designation: {
            type: 'string',
            required: true
        },
        ownerpercentage: {
            type: "float",
            required: true
        },
        ownerid: {
            type: 'integer',
            required: false
        }
    }
};