/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        amount: {
            type: "float",
            required: true
        },
        paymentdate: {
            type: 'date',
            required: true
        },
        paymenttype: {
            type: 'string',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        paymentid: {
            type: 'integer',
            required: false
        },
        clientaccountid: {
            type: 'integer',
            required: false
        }
    }
};