/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        approve: {
            type: 'date',
            required: true
        },
        paydate: {
            type: 'date',
            required: true
        },
        payfrom: {
            type: 'date',
            required: true
        },
        payto: {
            type: 'date',
            required: true
        },
        prepearedate: {
            type: 'date',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        tax: {
            type: "float",
            required: true
        },
        totalgrosspay: {
            type: "float",
            required: true
        },
        totalnetpay: {
            type: "float",
            required: true
        },
        chartofaccountid: {
            type: 'integer',
            required: true
        },
        payrollid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};