/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        title: {
            type: 'string',
            required: true
        },
        firstname: {
            type: 'string',
            required: true
        },
        lastname: {
            type: 'string',
            required: true
        },
        dateofbirth: {
            type: 'date',
            required: true
        },
        gender: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        mobileno: {
            type: 'string',
            required: true
        },
        maritalstatus: {
            type: 'string',
            required: true
        },
        personid: {
            type: 'integer',
            required: false
        }
    }
};