/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        purchaserequestid: {
            type: 'integer',
            required: false
        },
        departmentid: {
            type: 'integer',
            required: true
        },
        date: {
            type: 'date',
            required: true
        },
        status: {
            type: 'string',
            required: true
        }
    }
};