/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        date: {
            type: 'date',
            required: true
        },
        discount: {
            type: 'integer',
            required: true
        },
        ordertotal: {
            type: "float",
            required: true
        },
        shippingdate: {
            type: 'date',
            required: true
        },
        tex: {
            type: "float",
            required: true
        },
        vat: {
            type: "float",
            required: true
        },
        nettotal: {
            type: "float",
            required: true
        },
        purchaseorderid: {
            type: 'integer',
            required: false
        },
        salescontractid: {
            type: 'integer',
            required: true
        },
        localid: {
            type: 'integer',
            required: true
        },
        purchaserequestid: {
            type: 'integer',
            required: true
        },
        qutationid: {
            type: 'integer',
            required: true
        }
    }
};