/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        itemid: {
            type: 'integer',
            required: true
        },
        quantity: {
            type: "float",
            required: true
        },
        price: {
            type: "float",
            required: true
        },
        approved: {
            type: 'boolean',
            required: true
        },
        qutationid: {
            type: 'integer',
            required: false
        },
        purchaserequestid: {
            type: 'integer',
            required: true
        },
        supplierid: {
            type: 'integer',
            required: true
        },
        purchaserequestcartid: {
            type: 'integer',
            required: true
        }
    }
};