/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        overtimerate: {
            type: "float",
            required: true
        },
        profiletype: {
            type: 'string',
            required: true
        },
        providentfund: {
            type: "float",
            required: true
        },
        taxrate: {
            type: "float",
            required: true
        },
        salaryprofileid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        },
        hourlyrate: {
            type: "float",
            required: true
        },
        commissionrate: {
            type: "float",
            required: true
        },
        paymenttype: {
            type: 'string',
            required: true
        }
    }
};