/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        destination: {
            type: 'string',
            required: true
        },
        purcheaseorderinfo: {
            type: 'string',
            required: true
        },
        source: {
            type: 'string',
            required: true
        },
        transportationmethod: {
            type: 'string',
            required: true
        },
        shipmentid: {
            type: 'integer',
            required: false
        },
        purchaseorderid: {
            type: 'integer',
            required: true
        },
        warehouseid: {
            type: 'integer',
            required: true
        }
    }
};