/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        stocktrackingdate: {
            type: 'date',
            required: true
        },
        quantityinstock: {
            type: "float",
            default: 0,
            required: true
        },
        stocklevelid: {
            type: 'integer',
            required: false
        },
        itemid: {
            type: 'integer',
            required: false
        }
    }
};