/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        accountname: {
            type: 'string',
            required: true
        },
        accountno: {
            type: 'string',
            required: true
        },
        address: {
            type: 'string',
            required: true
        },
        branch: {
            type: 'string',
            required: true
        },
        subsidiaryaccountid: {
            type: 'integer',
            required: false
        },
        chartofaccountid: {
            type: 'integer',
            required: false
        }
    }
};