/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        supplierid: {
            type: 'integer',
            required: false
        },
        departmentid: {
            type: 'integer',
            required: true
        },
        subsidiaryaccountid: {
            type: 'integer',
            required: true
        },
        type: {
            type: 'string',
            required: true
        },
        category: {
            type: 'string',
            required: true
        }
    }
};