/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        attendancedate: {
            type: 'date',
            required: true
        },
        present: {
            type: 'boolean',
            required: true
        },
        timesin: {
            type: 'datetime',
            required: true
        },
        timesout: {
            type: 'datetime',
            required: true
        },
        timesheetid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};