/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        date: {
            type: 'date',
            required: true
        },
        transactiontitle: {
            type: 'string',
            required: true
        },
        transactionid: {
            type: 'integer',
            required: false
        },
        branchid: {
            type: 'integer',
            required: true
        },
        financialyearid: {
            type: 'integer',
            required: false
        },
        entrydatetime: {
            type: 'datetime',
            required: true
        },
        userid: {
            type: 'integer',
            required: false
        },
        paymentid: {
            type: 'integer',
            required: true
        }
    }
};