/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        createdat: {
            type: 'datetime',
            required: false
        },
        updatedat: {
            type: 'datetime',
            required: false
        },
        roleid: {
            type: 'integer',
            required: false
        },
        userid: {
            type: 'integer',
            required: false
        }
    }
};