/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        id: {
            type: 'integer',
            required: false
        },
        name: {
            type: 'string',
            required: true
        },
        username: {
            type: 'string',
            required: true
        },
        email: {
            type: 'string',
            required: true
        },
        password: {
            type: 'string',
            required: true
        },
        createdat: {
            type: 'datetime',
            required: false
        },
        updatedat: {
            type: 'datetime',
            required: false
        }
    }
};