/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        type: {
            type: 'string',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        loadingcapacity: {
            type: 'string',
            required: true
        },
        vehicleno: {
            type: 'string',
            required: true
        },
        drivername: {
            type: 'string',
            required: true
        },
        vehicleid: {
            type: 'integer',
            required: false
        }
    }
};