/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        branchid: {
            type: 'integer',
            required: true
        },
        date: {
            type: 'date',
            required: true
        },
        transactionid: {
            type: 'integer',
            required: true
        },
        transactiontitle: {
            type: 'string',
            required: true
        },
        categorytype: {
            type: 'string',
            required: true
        },
        accountname: {
            type: 'string',
            required: true
        },
        journalid: {
            type: 'integer',
            required: true
        },
        financialyearid: {
            type: 'integer',
            required: true
        },
        debitcredit: {
            type: 'string',
            required: true
        },
        amount: {
            type: "float",
            required: true
        }
    }
};