/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        supplierid: {
            type: 'integer',
            required: true
        },
        departmentid: {
            type: 'integer',
            required: true
        },
        subsidiaryaccountid: {
            type: 'integer',
            required: true
        },
        type: {
            type: 'string',
            required: true
        },
        organizationid: {
            type: 'integer',
            required: true
        },
        companyname: {
            type: 'string',
            required: true
        },
        contactpersonname: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        contactno: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        website: {
            type: 'string',
            required: true
        }
    }
};