/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        clientid: {
            type: 'integer',
            required: true
        },
        date: {
            type: 'date',
            required: true
        },
        companyname: {
            type: 'string',
            required: true
        },
        contactpersonname: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        contactno: {
            type: 'string',
            required: true
        },
        emailaddress: {
            type: 'string',
            required: true
        },
        website: {
            type: 'string',
            required: true
        },
        addressline1: {
            type: 'string',
            required: true
        },
        addressline2: {
            type: 'string',
            required: true
        },
        postcode: {
            type: 'string',
            required: true
        },
        city: {
            type: 'string',
            required: true
        },
        country: {
            type: 'string',
            required: true
        }
    }
};