/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        contactno: {
            type: 'string',
            required: true
        },
        location: {
            type: 'string',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        factoryid: {
            type: 'integer',
            required: false
        },
        inventorydate: {
            type: 'date',
            required: true
        },
        warehouseid: {
            type: 'integer',
            required: false
        },
        deliveryid: {
            type: 'integer',
            required: true
        },
        createdat: {
            required: true
        },
        updatedat: {
            required: true
        }
    }
};