/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 's_tbl_AcademicHistory',
    primaryKey: 'academicHistoryID',

    attributes: {
        id: false,
        degreename: {
            type: 'string',
            required: true
        },
        institutionname: {
            type: 'string',
            required: true
        },
        awardingbody: {
            type: 'string',
            required: true
        },
        passingyear: {
            type: 'integer',
            required: true
        },
        result: {
            type: 'string',
            required: true
        },
        academicHistoryID: {
            type: 'number',
            unique: true,
            required: true,
            'autoIncrement': true
          },
        personid: {
            type: 'integer',
            required: true
        }
    }
};