/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        adjustmenttype: {
            type: 'string',
            required: true
        },
        amount: {
            type: "float",
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        adjustmenthead: {
            type: 'string',
            required: true
        },
        adjustmentid: {
            type: 'integer',
            required: false
        },
        wagesid: {
            type: 'integer',
            required: false
        },
        loanid: {
            type: 'integer',
            required: false
        }
    }
};