/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'm_tbl_BillingAddress',
    primaryKey: 'billingAddressID',

    attributes: {
        id: false, 
        billingAddressID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
          },       
      
          addressLine1: {
            type: 'string',
            required: true
        },
        addressLine2: {
            type: 'string',
            required:false,
            defaultsTo:''
        },
        city: {
            type: 'string',
            required: false,
            defaultsTo:''
        },
        country: {
            type: 'string',
            required:false,
            defaultsTo:''
        },
        name: {
            type: 'string',
            required: true
        },
        postcode: {
            type: 'string',
            required: false,
            defaultsTo:''
        },
        contactNo: {
            type: 'string',
            required:true
        },
        customerOrderID: {
            type: 'integer',
            required: false
        }
    },
    
    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    customerOrderID: { 
        model: 'Customerorder'
      },
     
};