/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        date: { type: 'ref', 
                columnType: 'datetime', 
                required: true
            },    
       
        quantity: {
            type: "float",
            required: true
        },
        registrationno: {
            type: 'string',
            required: true
        },
        iteminvoicevalue: {
            type: "float",
            required: true
        },
        totaltaxamount: {
            type: "float",
            required: true
        },
        totalaccessablevalue: {
            type: "float",
            required: true
        },
        billofentryid: {
            type: 'integer',
            required: false
        },
        lettercreditid: {
            type: 'integer',
            required: true
        },
        cnfagentid: {
            type: 'integer',
            required: true
        }
    }
};