/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {

    tableName: 'i_tbl_Category',
    primaryKey: 'categoryID',


    attributes: {        
        id: false,
        
        categoryID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
        },    
        categoryName: {
            type: 'string',
            required: true
        },
        description: {
            type: 'string',
            required: true
        },
        level: {
            type: 'integer',
            required: false
        },
        hasSubCategory: {
            type: 'boolean',
            required: false
        },

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

        item: { 
            collection: 'Item',
            via: 'categoryID'
          },
    },
    
};