/**
	Generated by sails-inverse-model
	Date:Mon Dec 02 2019 13:58:25 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
  tableName: 'a_tbl_ChartOfAccount',
  primaryKey: 'chartOfAccountID',

  
  attributes: {
    id: false,

    chartOfAccountID:{
      type: 'number',
      unique: true,
      'autoIncrement': true 
    },
    categoryType: {
          type: 'string',
          required: true
      },
      accountName: {
          type: 'string',
          required: true
      },
      desription: {
          type: 'string',
          required: true
      },
      underCategory: {
          type: 'string',
          required: true
      },
      /*natureType: {
          type: 'string',
          required: true
      }, */  
      
      
    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
 // Add a reference to ChartOfAccount 

 /*journals: { 
    collection: 'Journal',
    via: 'chartOfAccountID'
  },*/
  subsidiaryaccounts: { 
    collection: 'Subsidiaryaccount',
    via: 'chartOfAccountID'
  },
  }
};