/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 's_tbl_Client',  
    primaryKey: 'clientID',


    attributes: {
        id: false,
        clientType: {
            type: 'string',
            required: true
        },
        date: { 
            type: 'ref', 
            columnType: 'datetime', 
            required: true
        },    
        clientID:{
            type: 'number',
            unique: true,
            'autoIncrement': true 
            },

        organizationID: {
            type: 'integer',
            required: true
        },
      /*  subSidiaryAccountID: {
            type: 'integer',
            required: true
        },*/
    

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝

    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    // Add a reference to Branch
    
    agent: {
        collection:'thirdpartyagent',
        via: 'clientID'
      },
    contactinfo: {
        collection:'contactinfo',
        via: 'clientID'
      },
    owner: {
        collection:'owner',
        via: 'clientID'
      },
    
    person: {
        collection:'person',
        via: 'clientID'
      },
   
     
    }
};