/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  tableName: 's_tbl_ClientAccount',
  primaryKey: 'clientAccountID',

    attributes: {
        accountName: {
            type: 'string',
            required: true
        },
        accountNo: {
            type: 'string',
            required: true
        },        
        joiningDate: { type: 'ref', 
                columnType: 'datetime', 
                required: false
            },    
        active: {
            type: 'boolean',
            required: false
        },
        suspended: {
            type: 'boolean',
            required: false
        },
        accountCreditLimit: {
            type: "float",
            required: false
        },
        remarks: {
            type: 'string',
            required:false
        },
       
        id:false,
        clientAccountID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
        },
        clientID: {
            type: 'integer',
            required: true
        },
        organizationID: {
            type: 'integer',
            required: true
        }
    }
};