/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  // Name table in database
  tableName: 's_tbl_Company',
  primaryKey: 'companyID',

  attributes: {
        id: false,        

        companyName: {
            type: 'string',
            required: true
        },
        contactPersonName: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        contactNo: {
            type: 'string',
            required: true
        },
        emailAddress: {
            type: 'string',
            required: true
        },
        website: {
            type: 'string',
            required: true
        },
        companyID: {
            type: 'number',
            unique: true,
            'autoIncrement': true 
          },
    }
};