/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 's_tbl_ContactInfo',  
    primaryKey: 'contactID',

    attributes: {
        id: false,
        addressLine1: {
            'type': 'text',
            'required': true
        },
        addressLine2: {
            'type': 'text',
            'required':false
        },
        postcode: {
            type: 'string',
            required: false
        },
        city: {
            type: 'string',
            required: false
        },
        country: {
            type: 'string',
            required: false
        },
        contactID:{
            type: 'number',
            unique: true,
            'autoIncrement': true 
            },
        clientID: {
            type: 'integer',
            unique:true,
            required: true
        },
        emailAddress: {
            type: 'string',
            required: false
        },
        mobileNo1: {
            type: 'string',
            required: true
        },
        mobileNo2: {
            type: 'string',
            required: false
        },
        //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
        //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
        //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


        //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
        //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
        //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    // Add a reference to ChartOfAccount 
       
        clientID:{
            model:'client',
        },
        /*clientID: {
            model: 'VwCustomer'
        },*/
       
    }
};