/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'm_tbl_CustomerOrder',
    primaryKey: 'customerOrderID',
  

    attributes: {
        id: false,
        customerOrderID: {
          type: 'number',
          unique: true,
          'autoIncrement': true
        },  
        discount: {
            type: "float",
            required: true
        },
        orderDate: { type: 'ref', 
                columnType: 'datetime', 
                required: true
            }, 
        receiveDate: { type: 'ref', 
            columnType: 'datetime', 
            required: true
        },                  
        status: {
            type: 'string',
            required: true
        },
        orderTotal: {
            type: "float",
            required: true
        },
        netPay: {
            type: "float",
            required: true
        },
        clientAccountID: {
            type: 'integer',
            required: true
        },
        employeeID: {
            type: 'integer',
            required: true
        },
        branchID: {
            type: 'integer',
            required: true
        },
          
        
      //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    clientAccountID: { 
        model: 'Clientaccount'
      },
    details: { 
        collection: 'Orderdetails',
        via: 'customerOrderID'
      },
    employeeID: { 
        model: 'Employee'
      },    
    branchID: {       
        model: 'Branch'
      },
      
    },
};

