/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        deliveryid: {
            type: 'integer',
            required: false
        },
        customerorderid: {
            type: 'integer',
            required: false
        }
    }
};