/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'm_tbl_DeliveryAddress',
    primaryKey: 'deliveryAddressID',


    attributes: {
        id:false,
        deliveryAddressID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
        },       
        addressLine1: {
            type: 'string',
            required: true
        },
        addressLine2: {
            type: 'string',
            required: false
        },
        city: {
            type: 'string',
            required: false
        },
        name: {
            type: 'string',
            required: false
        },
        postcode: {
            type: 'string',
            required: false
        },
        mobileNo:{
            type: 'string',
            required: true
        },
        vehicleNo:{
            type: 'string',
            required: true
        },
        customerOrderID: {
            type: 'integer',
            required: true
        }
    },
    
    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    customerOrderID: { 
        model: 'Customerorder'
      },

};