/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        paymentmadeby: {
            type: 'string',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        disbusrmentpaymentid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        },
        payrollid: {
            type: 'integer',
            required: false
        }
    }
};