/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  // Name table in database
  tableName: 'p_tbl_Employee',
  primaryKey: 'employeeID',
    
    attributes: {

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝
         
        id: false,

       
        joningDate: { 
            type: 'ref', 
            columnType: 'datetime', 
            required: false
        }, 
        leavingDate: { 
            type: 'ref', 
            columnType: 'datetime', 
            required: false
        },         
        status: {
            'type': 'string',
            'required': false
        },
        designation: {
            'type': 'string',
            'required': false
        },
        employeeID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
        },
        warehouseID: {
            type: 'integer',
            required: false,
            defaultsTo:1
        },
        departmentID: {
            type: 'integer',
            required: false,
            defaultsTo:1
        },
        branchID: {
            type: 'integer',
            required: false,
            defaultsTo:1
        },
        factoryID: {
            type: 'integer',
            required: false,
            defaultsTo:1
        },
        organizationID: {
            type: 'integer',
            required: false,
            defaultsTo:1
        },
        personID: {
            type: 'integer',
            required:true
        }

    }
};