/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        designation: {
            type: 'string',
            required: true
        },
        organizationname: {
            type: 'string',
            required: true
        },
        address: {
            type: 'string',
            required: true
        },
        
        joiningdate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        leavingdate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        employmenthistoryid: {
            type: 'integer',
            required: false
        },
        personid: {
            type: 'integer',
            required: true
        }
    }
};