/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = { 
    tableName: 'a_tbl_FinancialYear', 
    primaryKey: 'financialYearID',

      
    attributes: {   
        id: false,
        
        startDate: {
            type: 'ref', 
            columnType: 'timestamp',
            required: true
        },
        endDate: {
            type: 'ref', 
            columnType: 'timestamp',
            required: true
        },
        financialYearID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
          },
        yearName: {
            type: 'string', 
            required: true,
            unique: true
        },          
    }
};