/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        nationality: {
            type: 'string',
            required: true
        },
        passportno: {
            type: 'string',
            required: true
        },
        foreignvehicleid: {
            type: 'integer',
            required: false
        },
        foreignshipmentid: {
            type: 'integer',
            required: true
        }
    }
};