/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        placeofloading: {
            type: 'string',
            required: true
        },
        placeofunloading: {
            type: 'string',
            required: true
        },
        customsname: {
            type: 'string',
            required: true
        },
        route: {
            type: 'string',
            required: true
        },
        foreignshipmentid: {
            type: 'integer',
            required: false
        },
        billofentryid: {
            type: 'integer',
            required: true
        }
    }
};