/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
       
  tableName: 'i_tbl_Item',
  primaryKey: 'itemID',

  attributes: {
        id: false,
    
        barcode: {
            type: 'string',
            required:false
        },
        description:{
            type: 'string',
            required: false
        },
        discount: {
            type: "float",
            required: false
        },
        images:{
            type: 'string',
            required: false
        },
        itemType: {
            type: 'string',
            required: false
        },
        maxOrderQuantity:{
            type: 'integer',
            required:false
        },
        name:{
            type: 'string',
            required: true
        },
        qrCode: {
            type: 'string',
            required: false
        },
        salePrice:{
            type: "float",
            required: false
        },
        unitPrice: {
            type: "float",
            required: false
        },
        publish: {
            type: 'boolean',
            required: false
        },
        categoryID: {
            type: 'integer',
            required: true
        },    
        
        itemID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
          },    
        sku: {
            type: 'string',
            required: false
        },

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

    categoryID: { 
            model: 'Category'
          },
    }
};