/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        leavedate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        leavefrom: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        leaveto: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        leavetype: {
            type: 'string',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        totaldays: {
            type: 'integer',
            required: true
        },
        leaveid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};