/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'b_tbl_LetterCredit',
    primaryKey: 'letterCreditID',

    attributes: {
        id: false,
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        HSCode: {
            type: 'string',
            required: true
        },
        IRCERCNo: {
            type: 'string',
            required: true
        },
        LCAFNo: {
            type: 'string',
            required: true
        },
        LCAFDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        LCDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        LCNo: {
            type: 'string',
            required: true
        },
        nameOfCarrier: {
            type: 'string',
            required: true
        },
        nationality: {
            type: 'string',
            required: true
        },
        placeOfLoading: {
            type: 'string',
            required: true
        },
        placeOfUnloading: {
            type: 'string',
            required: true
        },
        vatRegistrationNo: {
            type: 'string',
            required: true
        },
        currency: {
            type: 'string',
            required: true
        },
        insuranceCoverNoteNo: {
            type: 'string',
            required: true
        },
        recevingBank: {
            type: 'string',
            required: true
        },
        letterCreditID: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
          },
        insuranceID: {
            type: 'integer',
            required: true
        },
        subSidiaryAccountID: {
            type: 'integer',
            required: true
        },
        salesContractID:{
            type: 'integer',
            required: true
        }
    }
};