/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        loanamount: {
            type: "float",
            required: true
        },
        loandate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        payingdate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        remarks: {
            type: 'string',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        loanid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};