/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        basicsalary: {
            type: "float",
            required: true
        },
        convince: {
            type: "float",
            required: true
        },
        festivalbonus: {
            type: "float",
            required: true
        },
        houserent: {
            type: "float",
            required: true
        },
        medicalallowance: {
            type: "float",
            required: true
        },
        otherallowance: {
            type: "float",
            required: true
        },
        increment: {
            type: "float",
            required: true
        },
        monthlyid: {
            type: 'integer',
            required: false
        }
    }
};