/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'm_tbl_OrderDetails',
    primaryKey: 'orderDetailsID',


    attributes: {
        id: false,

        orderDetailsID: {
          type: 'number',
          unique: true,
          'autoIncrement': true
        },  
        discount: {
            type: "float",
            required: true
        },
        quantity: {
            type: 'integer',
            required: true
        },
        unitPrice: {
            type: "float",
            required: true
        },
        total: {
            type: "float",
            required: true
        },        
        customerOrderID: {
            type: 'integer',
            required: true
        },
        itemID: {
            type: 'integer',
            required: true
        },
    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    customerOrderID: { 
        model: 'Customerorder'
      },
    
    itemID: { 
        model: 'Item'
      },    
      
  
    },
    
  
  
};