/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        overtimedate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        fromtime: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        totalhour: {
            type: "float",
            required: true
        },
        totime: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        overtimeid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};