/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'o_tbl_Owner',  
    primaryKey: 'ownerID',

    attributes: {
        id: false,        
        designation: {
            type: 'string',
            required: false
        },
        ownerID:{
            type: 'number',
            unique: true,
            'autoIncrement': true 
            },
        IRCLicenseNo: {
            type: 'string',
            required: false
        },
        TradeLicenseNo: {
            type: 'string',
            required: false
        },
        LicenseExpireDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: false
        },
        clientID:{
            type: 'number',
            required: true,
            unique: true,
        },
      
        //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
        //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
        //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


        //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
        //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
        //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
    // Add a reference to ChartOfAccount 
        clientID:{
            model:'client',
            unique: true
        },
        
    }

};