/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {    
    tableName: 'a_tbl_Payment',
    primaryKey: 'paymentID',

  
    attributes: {
        id: false,
        
        paymentID: {
          type: 'number',
          unique: true,
          'autoIncrement': true
        },  

        amount: {
            type: "float",
            required: true
        },
        paymentDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        paymentType: {
            type: 'string',
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        clientAccountID: {
            type: 'integer',
            required: false
        }
    },

       
    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
 // Add a reference to ChartOfAccount 
 
 chartOfAccountID: { 
    model: 'Chartofaccount'
  },
  
};