/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'b_tbl_PurchaseRequestCart',
    primaryKey: 'purchaseRequestCartID',

    attributes: {
        id: false,
        purchaseRequestCartID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
          },
        
        itemID: {
            type: 'integer',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        quantity: {
            type: "float",
            required: false
        },
        weight: {
            type: "float",
            required: false
        },
        unitPrice: {
            type: "float",
            required: false
        },
        purchaseRequestID: {
            type: 'integer',
            required: true
        }
        
    }
};