/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
            
    tableName: 'b_tbl_PurchaseRequest',
    primaryKey: 'purchaseRequestID',

    attributes: {
        id: false,
        purchaseRequestID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
          },
        departmentID: {
            type: 'integer',
            required: true
        },
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        status: {
            type: 'string',
            required: true
        }
    }
};