/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
        
    tableName: 'b_tbl_PurchaseOrder',
    primaryKey: 'purchaseOrderID',


    attributes: {
        id: false,
   
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        discount: {
            type: 'integer',
            required: false
        },
        orderTotal: {
            type: "float",
            required: true
        },
        shippingDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        tax: {
            type: "float",
            required: false
        },
        vat: {
            type: "float",
            required: false
        },
        netTotal: {
            type: "float",
            required: true
        },
        purchaseOrderID: {
          type: 'number',
          unique: true,
          'autoIncrement': true
        },
       /* salesContractID: {
            type: 'integer',
            required: false
        },*/
        localID: {
            type: 'integer',
            required: true
        },  
        purchaseRequestID: {
            type: 'integer',
            required: true
        },
       /* qutationID: {
            type: 'integer',
            required: false
        },*/
        branchID: {
            type: 'integer',
            required: true,
          },
        

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
 // Add a reference to Organization      
    branchID: {       
            model: 'Branch'
          },
    details: {
            collection: 'purchaseorderdetails',
            via: 'purchaseOrderID'
          },
    contract: {
            collection: 'salescontract',
            via: 'purchaseOrderID'
          }
            
    },
     
};