/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'b_tbl_Qutation',
    primaryKey: 'id',
  
    attributes: {
        itemID: {
            type: 'integer',
            required: true
        },
        quantity: {
            type: "float",
            required: true
        },
        price: {
            type: "float",
            required: true
        },
        approved: {
            type: 'boolean',
            required: true
        },
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'qutationID'
          },
          purchaseRequestID: {
            type: 'integer',
            required: true
        },
        supplierID: {
            type: 'integer',
            required: true
        },
        purchaseRequestCartID: {
            type: 'integer',
            required: true
        }
    }
};