/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        title: {
            type: 'string',
            required: true
        },
        fullname: {
            type: 'string',
            required: true
        },
        position: {
            type: 'string',
            required: true
        },
        organization: {
            type: 'string',
            required: true
        },
        relation: {
            type: 'string',
            required: true
        },
        refereesid: {
            type: 'integer',
            required: false
        },
        personid: {
            type: 'integer',
            required: true
        }
    }
};