/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'p_tbl_SalaryProfile',
    primaryKey: 'salaryProfileID',
  
    attributes: {
        id:false,
        salaryProfileID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
        },
        overtimeRate: {
            type: "float",
            required: false
        },
        profileType: {
            type: 'string',
            required:false
        },
        providentFund: {
            type: "float",
            required: false
        },
        taxRate: {
            type: "float",
            required: false
        },
        employeeID: {
            type: 'integer',
            required: true
        },
        hourlyRate: {
            type: "float",
            required: true
        },
        commissionRate: {
            type: "float",
            required: false
        },
        paymentType: {
            type: 'string',
            required: false
        }
    }
};