/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  tableName: 'b_tbl_SalesContract',
  primaryKey: 'salesContractID',

    attributes: {
        id: false,
        salesContractID: {
            type: 'number',
            unique: true,
            'autoIncrement': true
          },
     
        paymentTerms: {
            type: 'string',
            required: true
        },
        isImported: {
            type: 'boolean',
            required: true
        },
        bankName: {
            type: 'string',
            required: true
        },
        contractNo: {
            type: 'string',
            required: true
        },
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        deliveryPeriodFrom: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        deliveryPeriodTo: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        iECNo: {
            type: 'string',
            required: true
        },
        route: {
            type: 'string',
            required: true
        },
        determinationOfMeserment: {
            type: 'string',
            required: true
        },
        modeOfTransport: {
            type: 'string',
            required: true
        },
        paymentMethod: {
            type: 'string',
            required: true
        },
      /*  letterCreditID: {
            type: 'integer',
            required: true
        },*/
        witnessID: {
            type: 'integer',
            required: true
        },
        internationalID: {
            type: 'integer',
            required: true
        },
        purchaseOrderID: {
            type: 'integer',
            required: true
        },

        purchaseOrderID: {
            model: 'purchaseorder'
          }
    }
};