/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
           
  tableName: 'i_tbl_StockLevel',
  primaryKey: 'stockLevelID',

    attributes: {
        id: false,
        stockLevelID:{
            type: 'number',
            unique: true,
            'autoIncrement': true
          },
        stockTrackingDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        quantityInStock: {
            type: "float",
            defaultsTo: 0,
            required: false
        },
       itemID: {
            type: 'number',
            required: false
        }
    }
};