/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        attendancedate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        present: {
            type: 'boolean',
            required: true
        },
        timesin: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        timesout: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        timesheetid: {
            type: 'integer',
            required: false
        },
        employeeid: {
            type: 'integer',
            required: true
        }
    }
};