/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        createdat: {
            type: 'ref', 
            columnType: 'datetime',
            required: false
        },
        updatedat: {
            type: 'ref', 
            columnType: 'datetime',
            required: false
        },
        roleid: {
            type: 'integer',
            required: false
        },
        userid: {
            type: 'integer',
            required: false
        }
    }
};