/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        accountname: {
            type: 'string',
            required: true
        },
        categorytype: {
            type: 'string',
            required: true
        },
        desription: {
            type: 'string',
            required: true
        },
        undercategory: {
            type: 'string',
            required: true
        },
        naturetype: {
            type: 'string',
            required: true
        },
        balance: {
            type: "float",
            required: true
        }
    }
};