/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'vw_a_journal',
    primaryKey: 'id',

    attributes: {
        branchID: {
            type: 'integer',
            required: true
        },
        transactionDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },        
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'transactionID'
          },

          transactionTitle: {
            type: 'string',
            required: true
        },
        categoryType: {
            type: 'string',
            required: true
        },
        accountName: {
            type: 'string',
            required: true
        },
        journalID: {
            type: 'integer',
            required: true
        },
        financialYearID: {
            type: 'integer',
            required: true
        },
        debitCredit: {
            type: 'string',
            required: true
        },
        amount: {
            type: "float",
            required: true
        }
    }
};