/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'vw_a_ledger',
    primaryKey: 'id',

    attributes: {
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'journalID'
          },
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        transactionTitle: {
            type: 'string',
            required: true
        },
        accountName: {
            type: 'string',
            required: true
        },
        debitCredit: {
            type: 'string',
            required: true
        },
        amount: {
            type: "float",
            required: true
        }
    }
};