/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    tableName: 'vw_corporate_customer',
    primaryKey: 'id',

    attributes: {
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'clientID'
          },
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        companyName: {
            type: 'string',
            required: true
        },
        contactPersonName: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        contactNo: {
            type: 'string',
            required: true
        },
        emailAddress: {
            type: 'string',
            required: true
        },
        website: {
            type: 'string',
            required: true
        },
        addressLine1: {
            type: 'string',
            required: true
        },
        addressLine2: {
            type: 'string',
            required: true
        },
        postcode: {
            type: 'string',
            required: true
        },
        city: {
            type: 'string',
            required: true
        },
        country: {
            type: 'string',
            required: true
        }
    }
};