/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  tableName: 'vw_customer',
  primaryKey: 'clientID',

    attributes: {
        id:false,
        clientID: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
          },
        accountName: {
            type: 'string',
            required: true
        },
        accountNo: {
            type: 'string',
            required: true
        },
        joiningDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        active: {
            type: 'boolean',
            required: true
        },  
        suspended: {
            type: 'boolean',
            required: true
        },
        accountCreditLimit: {
            type: 'number',
            required: true
        },  
        remarks:{
            type: 'string',
            required: true
        },
        clientAccountID: {
            type: 'integer',
            required: true
        },
        organizationID: {
            type: 'integer',
            required: true
        },
        date: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },        
        subSidiaryAccountID: {
            type: 'integer',
            required: true
        },

        /*contact:{
            collection: 'contactinfo',
            via: 'clientID'
          }*/
    }
};