/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        clientaccountid: {
            type: 'integer',
            required: true
        },
        due: {
            type: "float",
            required: true
        }
    }
};