/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
     // Name table in database
      tableName: 'vw_employees',
      primaryKey: 'id',

    attributes: {
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'employeeID'
        },
         title: {
            'type': 'string',
            'required': true
          },
          firstName: {
            'type': 'string',
            'required': true
          },
          lastName: {
            'type': 'string',
            'required': true
          },
          dateOfBirth:{
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        gender: {
          'type': 'string',
          'required': true
        },
        designation: {
            type: 'string',
            required: true
        },
        mobileNo: {
            'type': 'string',
            'required': false
          },
         
        emailAddress: {
          'type': 'string',
          'required': true
        }, 
        
        maritalStatus: {
          'type': 'string',
          'required': false
        },
        status: {
            type: 'string',
            required: true
        },
        joningDate: { 
            type: 'ref', 
            columnType: 'datetime', 
            required: true
        },
        leavingDate: { 
            type: 'ref', 
            columnType: 'datetime', 
            required: true
        },
        warehouseID: {
            type: 'integer',
            required: true
        },
        departmentID: {
            type: 'integer',
            required: true
        },
        branchID: {
            type: 'integer',
            required: true
        },
        factoryID: {
            type: 'integer',
            required: true
        },
        organizationID: {
            type: 'integer',
            required: true
        } 

    }
};