/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  tableName: 'vw_partners',
  primaryKey: 'id',

    attributes: {
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'organizationID'
          },
        organizationName: {
            type: 'integer',
            required: true
        },
        ownerID: {
            type: 'integer',
            required: true
        },        
        per_name: {
            type: 'string',
            required: true
        },
        mobileNo: {
            type: 'string',
            required: true
        },
        designation: {
            type: 'string',
            required: true
        },
        ownerpercentage: {
            type: 'number',
            required: true
        },
        IRCLicenseNo: {
            type: 'string',
            required: true
        },
        TradeLicenseNo: {
            type: 'string',
            required: true
        },
        LicenseExpireDate: {
            type: 'string',
            required: true
        },
        clientType: {
            type: 'string',
            required: true
        },
        addressLine1: {
            type: 'string',
            required: true
        },
        addressLine2: {
            type: 'string',
            required: true
        },
        postcode: {
            type: 'string',
            required: true
        },
        city: {
            type: 'string',
            required: true
        },
        country: {
            type: 'string',
            required: true
        },
    }
};