/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {

    tableName: 'vw_stock',
    primaryKey: 'id',

    attributes: {   
    
        sku: {
            type: 'string',
            required: true
        },
        barcode: {
            type: 'string',
            required: true
        },
        itemID: {
            type: 'integer',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        description: {
            type: 'string',
            required: true
        },
        images: {
            type: 'string',
            required: true
        },
        categoryName:{
            type: 'string',
            required: true
        },
        maxOrderQuantity: {
            type: 'string',
            required: true
        },
        itemType: {
            type: 'string',
            required: true
        },
        quantityInStock: {
            type: 'string',
            required: true
        },
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'stockLevelID'
          },
        
        stockTrackingDate: {
            type: 'ref', 
            columnType: 'datetime',
            required: true
        },
        discount: {
            type: 'float',
            required: true
        },
        
        unitPrice: {
            type: 'float',
            required: true
        },
        publish: {
            type: 'boolean',
            required: true
        },
    }
};