/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    
  tableName: 'vw_witness',
  primaryKey: 'id',

    attributes: {
        id: {
            type: 'number',
            unique: true,
            'autoIncrement': true, 
            columnName: 'clientID'
          },
        title: {
            type: 'string',
            required: true
        },        
        firstName: {
            type: 'string',
            required: true
        },
        lastName: {
            type: 'string',
            required: true
        },
        dateOfBirth: {
            type: 'string',
            required: true
        },
        gender: {
            type: 'string',
            required: true
        },
      /*  emailAddress: {
            type: 'string',
            required: false
        },*/
        maritalStatus: {
            type: 'string',
            required: true
        },        
        personID: {
            type: 'integer',
            required: true
        },        
        fathersName: {
            type: 'string',
            required: true
        },        
        mothersName: {
            type: 'string',
            required: true
        },        
        addressLine1: {
            type: 'string',
            required: true
        },        
        addressLine2: {
            type: 'string',
            required: true
        },        
        postcode: {
            type: 'string',
            required: true
        },   
        city: {
            type: 'string',
            required: true
        },
        country: {
            type: 'string',
            required: true
        },
        mobileNo1: {
            type: 'string',
            required: true
        },
        mobileNo2: {
            type: 'string',
            required: true
        },
    },
};