/**
	Generated by sails-inverse-model
	Date:Sat Nov 23 2019 17:44:33 GMT+0600 (Bangladesh Standard Time)
*/

module.exports = {
    attributes: {
        grossincome: {
            type: "float",
            required: true
        },
        netincome: {
            type: "float",
            required: true
        },
        overtime: {
            type: "float",
            required: true
        },
        status: {
            type: 'string',
            required: true
        },
        totalcommission: {
            type: "float",
            required: true
        },
        totalhour: {
            type: "float",
            required: true
        },
        wagesid: {
            type: 'integer',
            required: false
        },
        payrollid: {
            type: 'integer',
            required: false
        },
        salaryprofileid: {
            type: 'integer',
            required: false
        }
    }
};